USE TORNEO_FUTBOL;
-- Se crea una vista para ver el total de goles de cada equipo, se ordena por orden descendente.
-- Los datos se toman de los goles individuales de cada jugador.

CREATE VIEW SUMA_GOLES_EQUIPO AS
SELECT 
    	J.ID_EQUIPO
    ,	E.NOMBRE_EQUIPO
    ,	SUM(J.GOLES) AS TOTAL_GOLES
FROM 
    JUGADORES J
JOIN 
    EQUIPOS E ON J.ID_EQUIPO = E.ID_EQUIPO
GROUP BY 
    J.ID_EQUIPO, E.NOMBRE_EQUIPO;
    
SELECT 
* FROM SUMA_GOLES_EQUIPO
ORDER BY TOTAL_GOLES DESC;


CREATE VIEW Top10_Masculino_Amarillas AS
SELECT 
	j.NOMBRE_APELLIDO_JUG, j.TARJETAS_AMARILLAS
FROM 
	JUGADORES j
JOIN 
	EQUIPOS e ON j.ID_EQUIPO = e.ID_EQUIPO
JOIN 
	TORNEO t ON e.ID_TORNEO = t.ID_TORNEO
WHERE 
	t.NOMBRE_TORNEO LIKE '%Masculino%'
ORDER BY 
	j.TARJETAS_AMARILLAS DESC
LIMIT 10;

CREATE VIEW Top10_Masculino_Rojas AS
SELECT 
	j.NOMBRE_APELLIDO_JUG, j.TARJETAS_ROJAS
FROM 
	JUGADORES j
JOIN 
	EQUIPOS e ON j.ID_EQUIPO = e.ID_EQUIPO
JOIN 
	TORNEO t ON e.ID_TORNEO = t.ID_TORNEO
WHERE 
	t.NOMBRE_TORNEO LIKE '%Masculino%'
ORDER BY 
	j.TARJETAS_ROJAS DESC
LIMIT 10;


CREATE VIEW Top10_Femenino_Amarillas AS
SELECT 
	j.NOMBRE_APELLIDO_JUG, j.TARJETAS_AMARILLAS
FROM 
	JUGADORES j
JOIN 
	EQUIPOS e ON j.ID_EQUIPO = e.ID_EQUIPO
JOIN 
	TORNEO t ON e.ID_TORNEO = t.ID_TORNEO
WHERE 
	t.NOMBRE_TORNEO LIKE '%Femenino%'
ORDER BY 
	j.TARJETAS_AMARILLAS DESC
LIMIT 10;


CREATE VIEW Top10_Femenino_Rojas AS
SELECT 
	j.NOMBRE_APELLIDO_JUG, j.TARJETAS_ROJAS
FROM 
	JUGADORES j
JOIN 
	EQUIPOS e ON j.ID_EQUIPO = e.ID_EQUIPO
JOIN 
	TORNEO t ON e.ID_TORNEO = t.ID_TORNEO
WHERE 
	t.NOMBRE_TORNEO LIKE '%Femenino%'
ORDER BY 
	j.TARJETAS_ROJAS DESC
LIMIT 10;
